// <auto-generated />
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313225400_AddIssueReports")]
    partial class AddIssueReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BlazorApp.Models.IssueReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransportStateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IssueReports");
                });

            modelBuilder.Entity("BlazorApp.Models.RentalSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalCost")
                        .HasColumnType("REAL");

                    b.Property<int>("TransportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalSessions");
                });

            modelBuilder.Entity("BlazorApp.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transports", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BlazorApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorApp.Models.Bicycle", b =>
                {
                    b.HasBaseType("BlazorApp.Models.Transport");

                    b.Property<string>("FrameSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBasket")
                        .HasColumnType("INTEGER");

                    b.ToTable("Bicycles", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Models.Scooter", b =>
                {
                    b.HasBaseType("BlazorApp.Models.Transport");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotorPower")
                        .HasColumnType("INTEGER");

                    b.ToTable("Scooters", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Models.RentalSession", b =>
                {
                    b.HasOne("BlazorApp.Models.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorApp.Models.Bicycle", b =>
                {
                    b.HasOne("BlazorApp.Models.Transport", null)
                        .WithOne()
                        .HasForeignKey("BlazorApp.Models.Bicycle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp.Models.Scooter", b =>
                {
                    b.HasOne("BlazorApp.Models.Transport", null)
                        .WithOne()
                        .HasForeignKey("BlazorApp.Models.Scooter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
